version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: db_c
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: MangoReader
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: web_c
    depends_on:
      - db
    restart: always
    environment:
      - SECRET_KEY=al212#@!dkaskjdFSAF
      - PORT=8000
      - POSTGRES_CONNECTION_URI=postgresql://postgres:example@db:5432/MangoReader
      - POSTGRES_DB_NAME=MangoReader
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - .:/api

volumes: 
  postgres_data: