version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: db_c
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: MangoReader
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis: 
    image: redis 
    container_name: redis_c
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: web_c
    depends_on:
      - db 
      - redis 
    restart: always
    environment:
      - SECRET_KEY=al212#@!dkaskjdFSAF
      - PORT=8000
      - POSTGRES_CONNECTION_URI=postgresql://postgres:example@db:5432/MangoReader
      - POSTGRES_DB_NAME=MangoReader
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - .:/api


  celery:
    build: .
    container_name: celery_c 
    command: 
      celery -A run.celery worker --loglevel=INFO 
    restart: always
    environment:
      - SECRET_KEY=al212#@!dkaskjdFSAF
      - PORT=8000
      - POSTGRES_CONNECTION_URI=postgresql://postgres:example@db:5432/MangoReader
      - POSTGRES_DB_NAME=MangoReader
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db
    volumes:
      - .:/api

volumes: 
  postgres_data:
